### ISSUE TITLE
Auto Balance

### ISSUE THREAD

**Issue by GearBoxFox** [TitaniumTitans/2023ChargedUp#4]
Balance on the Charge station without any additional driver input. Use a gyro to balance, and then brake to stop from sliding off.

**Comment by Zoarial94** [comment]
Is there a reason these issues were recreated? I would much rather a discussion be had in the comments and the title updated to reflect the changes. Posts can be edited as well.

**Comment by GearBoxFox** [comment]
@Zoarial94 These issues were created so they were added to the project for this year. These are more for assigning people basic tasks than actually describing an issue.

**Comment by GearBoxFox** [comment]
Finished! This was finally finished recently right after the week 0 competition.
