### ISSUE TITLE
Create arm supersytem

### ISSUE THREAD

**Issue by Zoarial94** [TitaniumTitans/2023ChargedUp#78]
- [x] Encapsulate the 3 arm subsystems
- [x] Let a command addRequirement to the internal subsystems
- [x] The piecewise object should take in the current arm angle, and output the limits for the individual systems. 
- [x] The supersystem should add softlimits to all the subsystems
- [ ] When the supersystem is moving from one position to another, it should check for the boundaries between the piecewise intervals to ensure it enters the next boundary within its limits

**Comment by GearBoxFox** [comment]
Arew we still attempting logic for that last second on checking movement from one zone to another?

**Comment by Zoarial94** [comment]
@GearBoxFox I would still like to since it is another safety net, but I wont be able to work on anything until Sunday. Even then I will probably be beat. Its not a priority, so maybe after we get some more work on auto done.
