### ISSUE TITLE
On arm supersystem, detect stalling on motors to stop that action. 

### ISSUE THREAD

**Issue by Zoarial94** [TitaniumTitans/2023ChargedUp#83]
- Arm angle should stop on stall. (Should never be needed, but as a safety feature)
- Used to detect object in intake
- Likely not needed for extension

**Comment by Zoarial94** [comment]
The Spark Maxes don't seem to want to report a stall fault at any point. Another approach will be needed

**Comment by GearBoxFox** [comment]
We could theoretically check the current being drawn by the motor to implement a "stall fault" ourselves.
